apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  labels:
    name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP 
