apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
         - name:  WORDPRESS_DB_USER
           value: toto
         - name: WORDPRESS_DB_NAME
           value: wordpress
         - name:  WORDPRESS_DB_HOST
           value: mysql-deployement
         - name: WORDPRESS_DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: wordpress-secret
               key: wordpress_db_password
 
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        hostPath: 
          path: /data/wordpress
