apiVersion: v1
kind: Secret
metadata: 
   name: wordpress-secret
   namespace: wordpress
data: 
   wordpress_db_password: dG90bwo=
   mysql_password: dG90bwo=
   mysql_random_root_password: MQo=
type: Opaque
